inherit_from: .rubocop_todo.yml

AllCops:
  # rubocopの除外対象ファイル
  Exclude:
    - Gemfile

# =================style=====================

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# 文字列リテラルをfreezeしないを許可する
Style/FrozenStringLiteralComment:
  Enabled: false