inherit_from: .rubocop_todo.yml

AllCops:
  # rubocopの除外対象ファイル
  Exclude:
    - Gemfile
    - db/schema.rb
    - test/*

# =================style=====================

# 日本語のコメントを許可する
Style/AsciiComments:
  Enabled: false

# 文字列リテラルをfreezeしないを許可する
Style/FrozenStringLiteralComment:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false